DROP PROC PROC_THEMTAIXE
GO
CREATE 
PROC PROC_THEMTAIXE
	@TenTaiXe NVARCHAR(512),
	@KhaNangLai INT,
	@QuangDuong INT,
	@TenDangNhap VARCHAR(512),
	@MatKhau VARCHAR(512),
	@TinhTrang BIT,
	@MaTo INT
AS 
BEGIN TRAN 
	BEGIN TRY 
		IF EXISTS (SELECT * 
						FROM TAIXE
						WHERE TenDangNhap = @TenDangNhap)
		BEGIN 
			PRINT @TenDangNhap + N'ĐÃ TỒN TẠI TRONG HỆ THỐNG'
			ROLLBACK 
			RETURN 1
		END 
		IF @TenTaiXe IS NULL 
		BEGIN 
			PRINT N'TÊN TÀI XẾ KHÔNG ĐƯỢC TRỐNG'
			ROLLBACK
			RETURN 1
		END 
		IF @KhaNangLai < 0
		BEGIN
			PRINT N'KHẢ NĂNG LÁI PHẢI LÀ SỐ LỚN HƠN HOẶC BẰNG 0'
			ROLLBACK 
			RETURN 1 
		END 
		IF @QuangDuong <= 0
		BEGIN 
			PRINT N'QUÃNG ĐƯỜNG LÁI PHẢI LỚN HƠN 0'
			ROLLBACK 
			RETURN 1
		END 
		IF @TenDangNhap IS NULL
		BEGIN 
			PRINT N'TÊN ĐĂNG NHẬP KHÔNG ĐƯỢC TRỐNG'
			ROLLBACK 
			RETURN 1
		END 
		IF @MatKhau IS NULL
		BEGIN 
			PRINT N'MẬT KHẨU KHÔNG ĐƯỢC TRỐNG'
			ROLLBACK
			RETURN 1
		END 
		
		INSERT INTO TAIXE(TenTaiXe, KhaNangLai, QuangDuong, TenDangNhap, MatKhau, TinhTrang, MaTo) 
		VALUES(@TenTaiXe, @KhaNangLai, @QuangDuong, @TenDangNhap, @MatKhau, @TinhTrang, @MaTo)
		----
		WAITFOR DELAY '0:0:10'
		----
		ROLLBACK 
		RETURN 1
	END TRY 
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK 
		RETURN 1
	END CATCH 
COMMIT TRAN
RETURN 0
GO

--TRAN 2 READ TAI XE
DROP PROC PROC_DOCTAIXE
GO
CREATE 
PROC PROC_DOCTAIXE
	@TenDangNhap VARCHAR(512),
	@TenTaiXe NVARCHAR(512) OUT 
AS 
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	BEGIN TRY 
		IF NOT EXISTS (SELECT *
						FROM TAIXE
						WHERE TenDangNhap = @TenDangNhap)
		BEGIN 
			PRINT N'KHÔNG TỒN TẠI TÀI KHOẢN ' + @TenDangNhap
			ROLLBACK
			RETURN 1
		END 
		IF EXISTS (SELECT * 
					FROM TAIXE
					WHERE TenDangNhap = @TenDangNhap AND TinhTrang = 0)
		BEGIN 
			PRINT N'TÀI KHOẢN ' + @TenDangNhap + ' ĐÃ BỊ KHÓA'
			ROLLBACK 
			RETURN 1
		END 

		SET @TenTaiXe = (SELECT TenTaiXe FROM TAIXE WHERE TenDangNhap = @TenDangNhap)

	END TRY
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK 
		RETURN 1
	END CATCH 
COMMIT TRAN
GO