DROP PROC PROC_CAPNHATTENTAIXE
GO
CREATE 
PROC PROC_CAPNHATTENTAIXE
	@TenTaiXe NVARCHAR(512),
	@TenDangNhap VARCHAR(512)
AS 
BEGIN TRAN 
	BEGIN TRY 
		IF NOT EXISTS (SELECT * 
						FROM TAIXE
						WHERE TenDangNhap = @TenDangNhap)
		BEGIN 
			PRINT @TenDangNhap + N' KHÔNG TỒN TẠI TRONG HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END 
		IF @TenDangNhap IS NULL
		BEGIN 
			PRINT N'TÊN ĐĂNG NHẬP KHÔNG ĐƯỢC TRỐNG'
			ROLLBACK TRAN
			RETURN 1
		END 
		IF @TenTaiXe IS NULL
		BEGIN 
			PRINT N'TÊN TÀI XẾ KHÔNG ĐƯỢC TRỐNG'
			ROLLBACK TRAN
			RETURN 1
		END 
		UPDATE TAIXE
		SET TenTaiXe = @TenTaiXe
		WHERE TenDangNhap = @TenDangNhap
		----
		WAITFOR DELAY '0:0:10'
		----
		ROLLBACK TRAN
		RETURN 1
	END TRY 
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH 
COMMIT TRAN
RETURN 0
GO

--TRAN 2 READ TAI XE
DROP PROC PROC_DOCTAIXE
GO
CREATE 
PROC PROC_DOCTAIXE
	@TenDangNhap VARCHAR(512),
	@TenTaiXe NVARCHAR(512) OUT 
AS 
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	BEGIN TRY 
		IF NOT EXISTS (SELECT *
						FROM TAIXE
						WHERE TenDangNhap = @TenDangNhap)
		BEGIN 
			PRINT N'KHÔNG TỒN TẠI TÀI KHOẢN ' + @TenDangNhap
			ROLLBACK
			RETURN 1
		END 
		IF EXISTS (SELECT * 
					FROM TAIXE
					WHERE TenDangNhap = @TenDangNhap AND TinhTrang = 0)
		BEGIN 
			PRINT N'TÀI KHOẢN ' + @TenDangNhap + ' ĐÃ BỊ KHÓA'
			ROLLBACK 
			RETURN 1
		END 

		SET @TenTaiXe = (SELECT TenTaiXe FROM TAIXE WHERE TenDangNhap = @TenDangNhap)

	END TRY
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK 
		RETURN 1
	END CATCH 
COMMIT TRAN
GO