DROP PROC PROC_THEMKHANANGLAI
GO
CREATE 
PROC PROC_THEMKHANANGLAI
	@TenDangNhap VARCHAR(512),
	@SoTang INT
AS 
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT * 
				FROM TAIXE 
				WHERE TenDangNhap = @TenDangNhap)
		BEGIN
			PRINT @TenDangNhap + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 1
		END
		IF @SoTang <= 0
		BEGIN 
			PRINT N'KHẢ NĂNG LÁI KHÔNG HỢP LỆ'
			ROLLBACK TRAN
			RETURN 1
		END 
		DECLARE @KNLAI INT
		SET @KNLAI = (SELECT KHaNangLai 
						FROM TAIXE WITH (XLOCK)
						WHERE TenDangNhap = @TenDangNhap)
		-------
		WAITFOR DELAY '0:0:10'
		-------
		
		UPDATE TAIXE
		SET KhaNangLai = @SoTang + @KNLAI
		WHERE TenDangNhap = @TenDangNhap
	END TRY
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH 
COMMIT TRAN
RETURN 0
GO 

DROP PROC PROC_GIAMKHANANGLAI
GO
CREATE 
PROC PROC_GIAMKHANANGLAI
	@TenDangNhap VARCHAR(512),
	@SoGiam INT
AS 
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT * 
				FROM TAIXE 
				WHERE TenDangNhap = @TenDangNhap)
		BEGIN
			PRINT @TenDangNhap + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 1
		END
		IF @SoGiam <= 0
		BEGIN 
			PRINT N'KHẢ NĂNG LÁI KHÔNG HỢP LỆ'
			ROLLBACK TRAN
			RETURN 1
		END 
		DECLARE @KNLAI INT
		SET @KNLAI = (SELECT KHaNangLai 
						FROM TAIXE
						WHERE TenDangNhap = @TenDangNhap)
		
		UPDATE TAIXE
		SET KhaNangLai = @KNLAI - @SoGiam
		WHERE TenDangNhap = @TenDangNhap
	END TRY
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH 
COMMIT TRAN
RETURN 0
GO 




