DROP PROC PROC_CAPNHATTAIXE

GO 
CREATE
PROC PROC_CAPNHATTAIXE
	@TenDangNhap VARCHAR(512),
	@TinhTrangMoi BIT OUT
AS
BEGIN TRAN
	BEGIN TRY 
		IF NOT EXISTS (SELECT * 
							FROM TAIXE
							WHERE TenDangNhap = @TenDangNhap)
		BEGIN 
			PRINT @TenDangNhap + N' KHÔNG TỒN TẠI TRONG HỆ THỐNG'
			ROLLBACK
			RETURN 1
		END
		DECLARE @TinhTrangCu BIT
		SET @TinhTrangCu = (SELECT * FROM TAIXE WHERE TenDangNhap = @TenDangNhap)
		IF @TinhTrangCu = @TinhTrangMoi
		BEGIN
			PRINT N'CẬP NHẬT TÌNH TRẠNG THÀNH CÔNG'
			RETURN
		END 
		UPDATE TAIXE
		SET TinhTrang = @TinhTrangMoi
		WHERE TenDangNhap = @TenDangNhap
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK
	END CATCH 
COMMIT TRAN

GO 

DROP PROC PROC_DOCTINHTRANGTAIXE
GO
CREATE 
PROC PROC_DOCTINHTRANGTAIXE
	@TenDangNhap VARCHAR(512),
	@TinhTrangLan1 BIT OUT,
	@TinhTrangLan2 BIT OUT
AS 
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT *
						FROM TAIXE
						WHERE TenDangNhap = @TenDangNhap)
		BEGIN 
			PRINT N'KHÔNG TỒN TẠI TÀI KHOẢN ' + @TenDangNhap
			ROLLBACK 
			RETURN 1
		END 
		SET @TinhTrangLan1 = (SELECT TinhTrang FROM TAIXE WHERE TenDangNhap = @TenDangNhap)
		
		-----
		WAITFOR DELAY '0:0:10'
		-----

		SET @TinhTrangLan2 = (SELECT TinhTrang FROM TAIXE WHERE TenDangNhap = @TenDangNhap)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK 
		RETURN 1
	END CATCH
COMMIT TRAN 
GO

