USE [QuanLyLaiXe]
GO
------------------------
--- T1: CAP NHAT THONG TIN TUYEN DUONG ------
--- T2: XEM THONG TIN TUYEN DUONG ---

--- T1----
--DROP PROCEDURE GT_CAPNHATTUYENDUONGCREATE --ALTERPROC GT_CAPNHATTUYENDUONG	@MaTuyenDuong varchar(512),
	@TenTuyenDuong nvarchar(512),
	@ChieuDai intASBEGIN TRAN	BEGIN TRY		IF NOT EXISTS (SELECT * FROM TUYENDUONG WHERE MaTuyenDuong = @MaTuyenDuong)		BEGIN			PRINT @MaTuyenDuong + N' KHÔNG TỒN TẠI'			ROLLBACK TRAN			RETURN 		END		--ĐỂ TEST		WAITFOR DELAY '0:0:05'		---------		UPDATE TUYENDUONG SET TenTuyenDuong=@TenTuyenDuong, ChieuDai=@ChieuDai WHERE MaTuyenDuong=@MaTuyenDuong	END TRY	BEGIN CATCH		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN	END CATCHCOMMIT TRANGO--- T2: XEM THONG TIN TUYEN DUONG -----DROP PROCEDURE GT_XEMTHONGTINTUYENDUONGCREATE --ALTERPROC GT_XEMTHONGTINTUYENDUONG_FIX	@MaTuyenDuong varchar(512)ASBEGIN TRAN	SET TRAN ISOLATION LEVEL READ UNCOMMITTED	BEGIN TRY
	SELECT * FROM TUYENDUONG WHERE MaTuyenDuong = @MaTuyenDuong
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1	
	END CATCHCOMMIT TRANRETURN 0